//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDI_VFD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDI_VFD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectricalApps.
        /// </summary>
        internal static string dBName {
            get {
                return ResourceManager.GetString("dBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULSQL12T.
        /// </summary>
        internal static string dBServer {
            get {
                return ResourceManager.GetString("dBServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHRT_LST.
        /// </summary>
        internal static string tblChrtList {
            get {
                return ResourceManager.GetString("tblChrtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHRT_V1000.
        /// </summary>
        internal static string tblChrtV1000 {
            get {
                return ResourceManager.GetString("tblChrtV1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRV_V1000_FLT.
        /// </summary>
        internal static string tblDrvV1000Faults {
            get {
                return ResourceManager.GetString("tblDrvV1000Faults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRV_V1000_MON.
        /// </summary>
        internal static string tblDrvV1000Mons {
            get {
                return ResourceManager.GetString("tblDrvV1000Mons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRV_V1000_PARAM.
        /// </summary>
        internal static string tblDrvV1000Params {
            get {
                return ResourceManager.GetString("tblDrvV1000Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACH_DATA.
        /// </summary>
        internal static string tblMachData {
            get {
                return ResourceManager.GetString("tblMachData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACH_GEN_DATA.
        /// </summary>
        internal static string tblMachDataGen {
            get {
                return ResourceManager.GetString("tblMachDataGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACH_MTR_DEFS.
        /// </summary>
        internal static string tblMachDataMtrDefs {
            get {
                return ResourceManager.GetString("tblMachDataMtrDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTR_DATA.
        /// </summary>
        internal static string tblMtrData {
            get {
                return ResourceManager.GetString("tblMtrData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTR_DATA_FLC.
        /// </summary>
        internal static string tblMtrDataFLC {
            get {
                return ResourceManager.GetString("tblMtrDataFLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFD_LST.
        /// </summary>
        internal static string tblVFDList {
            get {
                return ResourceManager.GetString("tblVFDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon V1000 {
            get {
                object obj = ResourceManager.GetObject("V1000", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
